# Generated by Django 5.2.18 on 2026-10-07 00:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(help_text='Plain text only; paragraphs are preserved. Publish accurate store policies before going live.')),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_started', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('stripe_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser_key', models.UUIDField(db_index=True, editable=False)),
                ('cart_fingerprint', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid'), ('expired', 'Expired / canceled'), ('review', 'Payment requires review'), ('refunded', 'Fully refunded')], db_index=True, default='pending', max_length=20)),
                ('fulfillment', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('packing', 'Packing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='unfulfilled', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('tracking_url', models.URLField(blank=True, max_length=1000)),
                ('staff_notes', models.TextField(blank=True)),
                ('currency', models.CharField(default='usd', editable=False, max_length=3)),
                ('subtotal_cents', models.PositiveIntegerField(editable=False)),
                ('shipping_cents', models.PositiveIntegerField(default=0, editable=False)),
                ('tax_cents', models.PositiveIntegerField(default=0, editable=False)),
                ('total_cents', models.PositiveIntegerField(default=0, editable=False)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=255)),
                ('stripe_payment_intent', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('stripe_checkout_url', models.URLField(blank=True, editable=False, max_length=2000)),
                ('checkout_payload', models.JSONField(default=dict, editable=False)),
                ('customer_email', models.EmailField(blank=True, editable=False, max_length=254)),
                ('customer_name', models.CharField(blank=True, editable=False, max_length=240)),
                ('shipping_address', models.JSONField(blank=True, default=dict, editable=False)),
                ('reserved_until', models.DateTimeField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('stripe_session_id', ''), _negated=True), fields=('stripe_session_id',), name='unique_stripe_checkout')],
            },
        ),
        migrations.CreateModel(
            name='CheckoutState',
            fields=[
                ('browser_key', models.UUIDField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('brand', models.CharField(default='MERIDIAN', max_length=80)),
                ('collection', models.CharField(choices=[('dress', 'Dress watches'), ('dive', 'Dive watches'), ('chronograph', 'Chronographs')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))])),
                ('short_description', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('image', models.CharField(default='images/watch-noir.png', help_text='HTTPS image URL from your image host, or a bundled path such as images/watch-noir.png. Render does not retain local uploads.', max_length=1000)),
                ('image_alt', models.CharField(blank=True, max_length=220)),
                ('movement', models.CharField(blank=True, max_length=140)),
                ('case_size', models.CharField(blank=True, max_length=80)),
                ('material', models.CharField(blank=True, max_length=140)),
                ('water_resistance', models.CharField(blank=True, max_length=100)),
                ('strap', models.CharField(blank=True, max_length=140)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available units. Open checkouts reserve stock immediately; expired checkouts restore it. Do not include reserved units here.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=False, help_text='Sample product. Never accepted with live Stripe keys.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
                'indexes': [models.Index(fields=['is_active', 'collection'], name='shop_produc_is_acti_522ca1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.50'))), name='product_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_positive')],
            },
        ),
    ]
