# Generated by Django 5.2.18 on 2026-10-07 00:52

from django.db import migrations, models


def rebrand_existing_content(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Page = apps.get_model('shop', 'Page')
    Product.objects.filter(brand='MERIDIAN').update(brand='EIDREN')
    for page in Page.objects.filter(body__contains='Meridian'):
        page.body = page.body.replace('MERIDIAN', 'EIDREN').replace('Meridian', 'EIDREN')
        page.save(update_fields=['body'])


def restore_previous_brand(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Product.objects.filter(brand='EIDREN').update(brand='MERIDIAN')


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rebrand_existing_content, restore_previous_brand),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='EIDREN', max_length=80),
        ),
    ]
